language: python
python:
  - "2.7"


install:

    # command to install dependencies
    - python setup.py install


script:

    # command to run tests
    - python -m unittest cosmo.tests.test_celery
    - python -m unittest cloudify.tests.test_celery
