language: python
python:
  - "2.7"

install:
    - pip install https://github.com/cloudify-cosmo/cloudify-rest-client/archive/feature/CFY-783-add-support-for-cancel-execution.zip
    - pip install . -r requirements.txt
    - pip install flake8

script:
    - flake8 .
    - nosetests cloudify/tests --nologcapture --nocapture
