language: python
python:
  - "2.7"

install:
    - pip install . -r requirements.txt
    - pip install flake8

script:
    - flake8 . --exclude docs
    - nosetests cloudify/tests --nologcapture --nocapture
notifications:
    flowdock: 1f4ec6febcf1ac9b35ae6c1f0049471f
